# Generated by Django 4.1.3 on 2022-11-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_myuser_bio_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
