# Generated by Django 4.1.3 on 2022-11-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
    ]
