# Generated by Django 4.1.3 on 2022-11-07 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_profile_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='music',
        ),
    ]
