# Generated by Django 4.1.3 on 2022-11-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_profile_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
    ]
