# Generated by Django 4.1.3 on 2022-11-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_rename_name_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
    ]
