# Generated by Django 4.1.3 on 2022-11-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_rename_song_pic_track_songimg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='TrackModel',
        ),
    ]
