# Generated by Django 4.1.3 on 2022-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_rename_track_trackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
