# Generated by Django 4.1.3 on 2022-11-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_trackmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='songImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='songName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
