# Generated by Django 4.1.3 on 2022-11-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_trackmodel_file_alter_trackmodel_songimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dp',
            field=models.ImageField(blank=True, default='/static/images/turtle_TpDCiLF.jpeg', null=True, upload_to=''),
        ),
    ]
