# Generated by Django 4.1.3 on 2022-11-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_profilemodel_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dp',
            field=models.ImageField(blank=True, default='static/images/turtle_TpDCiLF.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='file',
            field=models.FileField(default='static/images/file_example_MP3_700KB_DY8xrM5.mp3', null=True, upload_to=''),
        ),
    ]
