# Generated by Django 4.1.3 on 2022-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_profilemodel_dp_alter_trackmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='contact',
            field=models.URLField(blank=True, null=True),
        ),
    ]
