# Generated by Django 4.1.3 on 2022-11-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_profilemodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='contact',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
