# Generated by Django 4.1.3 on 2022-11-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_profilemodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='contact',
            field=models.TextField(blank=True, default='#', max_length=200, null=True),
        ),
    ]
